- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  
  roles:
    - configure-server
    - setup-mysql
    - deploy-app

  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted
    - name: Restart Apache
      service:
        name: apache2
        state: restarted