---
- name: "Find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: Start postgresql
  service:
    name: postgresql
    enabled: yes
    state: started

- name: "Create app database"
  postgresql_db:
    state: present
    name: "laravel-realworld"
  become: yes
  become_user: postgres

- name: "Create db user"
  postgresql_user:
    state: present
    name: "admin"
    password: "Password@123"
  become: yes
  become_user: postgres

- name: "Grant db user access to app db"
  postgresql_privs:
    type: database
    database: "laravel-realworld"
    roles: "admin"
    grant_option: no
    privs: all
  become: yes
  become_user: postgres

- name: "Allow md5 connection for the db user"
  postgresql_pg_hba:
    dest: "~/data/pg_hba.conf"
    contype: host
    databases: all
    method: md5
    users: "admin"
    create: true
  become: yes
  become_user: postgres
  notify: restart postgres